---
- name: testing host variable
  hosts: all
  become: true
  vars:
          mystate: present
  tasks:
          - name: adding user
            user:
                    name: "{{ myuser }}"
                    state: "{{ mystate }}"

