---
- name: launching complete apache website
  hosts: all
  become: true
  tasks:
          - name: Restart everything
            command: echo "this task will restart the web services"
            notify: "restart web services"

  handlers:
          - name: Restart sshd
            service:
                    name: sshd
                    state: restarted
            listen: "restart web services"

          - name: Restart apache
            service:
                    name: apache2
                    state: restarted
            listen: "restart web services"

