---
- name: using handlers with practical example
  hosts: all
  become: true
  tasks: 
      - name: installing apache software
        apt:
                name: apache2
                state: present
      - name: installing telnet 
        apt:
                name: telnet
                state: present 
      - name: copy index.html
        copy:
                src: index.html
                dest: /var/www/html/index.html
        notify:
                - Restart apache
                - Restart telnet
  handlers:
      - name: start the apache2 service
        service:
                name: apache2
                state: restarted
      - name: install telnet
        apt:
                name: telnet
                state: present
