---
- name: loops YAML practice
  hosts: all
  become: true
  tasks:
          - name: loop
            debug:
                    msg: "{{ item }}"
            loop:
                    - one
                    - two

          - name: with_items
            debug:
                    msg: "{{ item }}"
            with_items:
                    - one
                    - two

          - name: with_indexed_items
            debug:
                    msg: "{{ item.0}} - {{ item.1 }}"
            with_indexed_items:
                    - one
                    - two

