- name: testing dictionary loop
  hosts: dev
  become: true
  tasks:
          - name: Using dict2items
            ansible.builtin.debug:
             msg: "{{ item.key }} - {{ item.value }}"
            loop: "{{ tag1 | dict2items }}"
            vars:
             tag1:
                 Environment: dev
                 Application: payment 

