---
- name: install nodejs
  hosts: dev
  gather_facts: true
  become: true
  tasks:
        - name: add apt key for nodesource
          apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

        - name: add repository for nodesource
          apt_repository:
                 repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
                 update_cache: no

        - name: install nodejs
          apt: name=nodejs
