---
- name: testing variables in playbook from separate var file
  hosts: all
  become: true
  vars_files:
          - myvars.yaml
  tasks:
          - name: installing software
            user:
              name: "{{ mypackage }}"
              state: "{{ mystate1 }}"
          - name: copy index.html
            copy:
              src: "{{ mysrc }}"
              dest: /var/www/html/index.html
          - name: start the service
            service:
              name: "{{ myservice }}"
              state: "{{ mystate2 }}"
