---
- name: testing var group separate file
  hosts: all
  become: true
  vars:
          mystate: present
  tasks:
          - name: adding user
            user:
                    name: "{{ myuser1 }}"
                    state: "{{ mystate }}"

          - name: adding groups
            user:
                    name: "{{ mygroup }}"
                    state: "{{ mystate }}"



