---
- name: testing separate host_vars directory with files
  hosts: all
  become: true
  vars:
          mystate: present
  tasks:
          - name: adding user
            user:
                    name: "{{ myuser }}"
                    state: "{{ mystate }}"
                    password: "{{ 'greenhat' | password_hash('sha512')}} "
