- name: testing our first playbook
  hosts: all
  become: true
  vars:
          mystate: absent 
          myusers:
                  - user102
                  - user103
                  - user104
  tasks:
          - name: adding user
            user:
                    name: "{{ item }}" 
                    state: "{{ mystate }}" 
            loop:
                    "{{ myusers }}"
            when:  ansible_memory_mb['real'].total > 7000

